### ISSUE TITLE
Error on deserialization "Could not find member ... on type" when MissingMemberHandling=error and there is no discriminator field on the dto

### ISSUE THREAD

**Issue by craffael** [manuc66/JsonSubTypes#170]
### Source/destination types

```csharp
public abstract class Animal
{
    protected Animal(string name)
    {
        Name = name;
    }
      
    public string Name { get; private set; }
    
}

public class Fox : Animal
{

    public Fox(string name) : base(name)
    {
    }
}
```

### Source/destination JSON

```javascript
{"type":"fox","name":"Foxy"}
```

### Expected behavior

If we want to deserialize the above json, no error should be thrown, even if SerializerSettings have `MissingMemberHandling=Error` and if the target object doesn't have the discriminator field `type`. 

### Actual behavior

The following error is thrown:
```
Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500
  Message=Could not find member 'type' on object of type 'Fox'. Path 'type', line 1, position 13.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2280
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 1968
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 497
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 309
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 173
   at JsonSubTypes.JsonSubtypes.ThreadStaticReadObject(JsonReader reader, JsonSerializer serializer, JToken jToken, Type targetType) in JsonSubTypes\JsonSubtypes.cs:line 399
   at JsonSubTypes.JsonSubtypes.ReadJson(JsonReader reader, Type objectType, JsonSerializer serializer) in JsonSubTypes\JsonSubtypes.cs:line 116
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2190
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 169
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 904
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 829
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 787
   at Program.<Main>$(String[] args) in C:\Users\veli\Downloads\TestJsonSubtypes\Program.cs:line 18
```

### Steps to reproduce

```csharp
var settings = new JsonSerializerSettings
{
    MissingMemberHandling = MissingMemberHandling.Error,
    Converters = new List<JsonConverter>(){JsonSubtypesConverterBuilder.Of(typeof(Animal), "type")
        .RegisterSubtype(typeof(Fox), "fox")
        .SerializeDiscriminatorProperty()
        .Build()
    }
};

var dto = JsonConvert.DeserializeObject<Animal>("{\"type\":\"fox\",\"name\":\"Foxy\"}", settings);
```

**Comment by craffael** [comment]
@manuc66 I just stumbled again upon this problem.
I think this is a "problem" specific to JsonSubtype because if I serialize a fox to to json, i get a field "type" (because I set SerializeDiscriminatorProperty() ). I would then expect that also deserialization from this works again, i.e.
```
JsonConvert.Deserialize(JsonConvert.Serialize(fox,settings),settings)
```
should work as expected...

Or from another angle: If we take the example in your Readme.md and add `MissingMemberHandling=Error`, it doesn't work anymore:

```
var settings = new JsonSerializerSettings();
settings.Converters.Add(JsonSubtypesConverterBuilder
    .Of<Animal>("Type") // type property is only defined here
    .RegisterSubtype<Cat>(AnimalType.Cat)
    .RegisterSubtype<Dog>(AnimalType.Dog)
    .SerializeDiscriminatorProperty() // ask to serialize the type property
    .Build());

settings.MissingMemberHandling = MissingMemberHandling.Error; // <-- If we add this it fails!

var cat = new Cat { Age = 11, Lives = 6 };

var json = JsonConvert.SerializeObject(cat, settings);

var result = JsonConvert.DeserializeObject<Animal>(json, settings);

public abstract class Animal
{
    public int Age { get; set; }
}

public class Dog : Animal
{
    public bool CanBark { get; set; } = true;
}

public class Cat : Animal
{
    public int Lives { get; set; } = 7;
}

public enum AnimalType
{
    Dog = 1,
    Cat = 2
}
```

**Comment by manuc66** [comment]
Hi @craffael

This library doesn't support deserializing a JSON with a property that only serves subtype mapping but is not present in the mapped class hierarchy, and I don't see any way to support it. One pragmatic way would have been to remove the property before creating a new reader here: https://github.com/manuc66/JsonSubTypes/blob/master/JsonSubTypes/JsonSubtypes.cs#L476 but unfortunately, I haven't found a working API in Newtonsoft.Json to do that.

The workaround is to either add the property to your object or remove MissingMemberHandling.Error

If you find a reasonable way to support it, I would be happy to ship it
